### ISSUE TITLE
RBAC error when creating roles

### ISSUE THREAD

**Issue by DikkiX** [DikkiX/Schoolproject#3]
Hi maybe u have an idea,

I followed the rbac guide again and now have new problems.
When creating an new Role and keeping the rule area empty, i get this error.

`PHP Warning – yii\base\ErrorException
file_put_contents(C:\xampp\htdocs\Schoolproject\backend/rbac/items.php): Failed to open stream: No such file or directory
1. in C:\xampp\htdocs\Schoolproject\vendor\yiisoft\yii2\rbac\PhpManager.phpat line 799
790791792793794795796797798799800801802803804805806807808    /**
     * Saves the authorization data to a PHP script file.
     *
     * @param array $data the authorization data
     * @param string $file the file path.
     * @see loadFromFile()
     */
    protected function saveToFile($data, $file)
    {
        file_put_contents($file, "<?php\n\nreturn " . VarDumper::export($data) . ";\n", LOCK_EX);
        $this->invalidateScriptCache($file);
    }
 
    /**
     * Invalidates precompiled script cache (such as OPCache or APC) for the given file.
     * @param string $file the file path.
     * @since 2.0.9
     */
    protected function invalidateScriptCache($file)`

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/45206636/211009136-44b11c29-489d-45d8-aef9-f679d91eaf92.png">
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/45206636/211009188-3f560a71-1331-443a-8dd6-33a36f12fc48.png">

**Comment by DikkiX** [comment]
It never the nguide doesnt talk about any rbac item

**Comment by DikkiX** [comment]
@Cuji12

**Comment by Cuji12** [comment]
Off the top of my head I'm not sure but I can see you've declared a components array twice in your common/config/main.php and your authManager twice - you should make sure there's no duplicates in that file, from the Yii2 RBAC docs: "In case of yii2-advanced-app the authManager should be declared only once in common/config/main.php."

**Comment by Cuji12** [comment]
Also make sure you've ran your migrations for RBAC via "yii migrate --migrationPath=@yii/rbac/migrations".

**Comment by Cuji12** [comment]
Looks like someone faced a similar issue here: https://forum.yiiframework.com/t/console-command-failed-solved/74195/12?page=2 which may help you too.

**Comment by DikkiX** [comment]
> Off the top of my head I'm not sure but I can see you've declared a components array twice in your common/config/main.php and your authManager twice - you should make sure there's no duplicates in that file, from the Yii2 RBAC docs: "In case of yii2-advanced-app the authManager should be declared only once in common/config/main.php."

i cant see an duplicate in my config

**Comment by DikkiX** [comment]
So, i found the page that directs it.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/45206636/211045676-1866fa27-1421-498a-894a-81add3a85a74.png">
 but i changed it but now it shows this.
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/45206636/211047928-3df0442b-dd50-4020-ab93-3b22cd2f8b3b.png">

it should't say backend. u know a way to fix this?

**Comment by DikkiX** [comment]
fixed it!

**Comment by Cuji12** [comment]
Haha nice one, assuming it was the issue where you were declaring RBAC - good luck with your project! On a side note, if you're interested in furthering your PHP education I'd recommend this [book](https://www.amazon.co.uk/PHP-Objects-Patterns-Practice-Enhancements/dp/1484267907/ref=asc_df_1484267907/?tag=googshopuk-21&linkCode=df0&hvadid=463212453779&hvpos=&hvnetw=g&hvrand=16332274277252641421&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1006912&hvtargid=pla-1051067752690&psc=1&th=1&psc=1).

**Comment by DikkiX** [comment]
> Haha nice one, assuming it was the issue where you were declaring RBAC - good luck with your project! On a side note, if you're interested in furthering your PHP education I'd recommend this [book](https://www.amazon.co.uk/PHP-Objects-Patterns-Practice-Enhancements/dp/1484267907/ref=asc_df_1484267907/?tag=googshopuk-21&linkCode=df0&hvadid=463212453779&hvpos=&hvnetw=g&hvrand=16332274277252641421&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1006912&hvtargid=pla-1051067752690&psc=1&th=1&psc=1).

Yess, thanks i will check the book for sure i need it!!!


One last issue tho,

I just went thru everything and found a problem.
When submitting in my form it does nothing, i dont even get an error just no response. u know this fix??
Its in my frontend view/overzicht
<img width="633" alt="image" src="https://user-images.githubusercontent.com/45206636/211579177-12a85290-529f-4de7-92bd-560054539ea7.png">
